#!/bin/bash
# CICD Diagnostic and Fix Script for cross_app iOS Deployment

echo "=== CROSS_APP iOS CICD DIAGNOSTIC TOOL ==="
echo "Last updated: $(date)"
echo ""

echo "1. CHECKING PROJECT STRUCTURE..."
echo "---------------------------------"
echo "Bundle Identifier:"
grep -A1 -B1 "PRODUCT_BUNDLE_IDENTIFIER" ios/Runner.xcodeproj/project.pbxproj | head -5
echo ""

echo "Team ID in Xcode project:"
grep "DEVELOPMENT_TEAM" ios/Runner.xcodeproj/project.pbxproj | head -1
echo ""

echo "2. CHECKING WORKFLOW CONFIGURATION..."
echo "-------------------------------------"
echo "Workflow file exists: $(ls -la .github/workflows/ios-release.yml 2>/dev/null && echo "✅" || echo "❌")"
echo ""

echo "3. CHECKING FASTLANE CONFIGURATION..."
echo "--------------------------------------"
echo "Fastfile exists: $(ls -la ios/fastlane/Fastfile 2>/dev/null && echo "✅" || echo "❌")"
echo "Gemfile exists: $(ls -la ios/Gemfile 2>/dev/null && echo "✅" || echo "❌")"
echo ""

echo "4. CHECKING GITHUB SECRETS (SIMULATED)..."
echo "------------------------------------------"
echo "Required secrets for workflow:"
echo "1. APP_STORE_CONNECT_API_KEY_ID"
echo "2. APP_STORE_CONNECT_API_ISSUER_ID" 
echo "3. APP_STORE_CONNECT_API_KEY_CONTENT"
echo "4. SUPABASE_URL"
echo "5. SUPABASE_ANON_KEY"
echo ""

echo "5. API KEY FORMAT VALIDATION..."
echo "--------------------------------"
echo "To validate your .p8 file:"
echo ""
echo "CORRECT PEM FORMAT:"
echo "-----BEGIN PRIVATE KEY-----"
echo "MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgI..."
echo "... (32 lines of base64 content) ..."
echo "-----END PRIVATE KEY-----"
echo ""
echo "FILE SIZE: Should be ~2.2KB (2200-2300 bytes)"
echo ""

echo "6. VERIFICATION STEPS:"
echo "----------------------"
echo "A. Check Apple Developer Portal:"
echo "   1. Go to https://appstoreconnect.apple.com/"
echo "   2. Users & Access → Keys"
echo "   3. Find your key and check:"
echo "      - ✅ Key ID matches APP_STORE_CONNECT_API_KEY_ID"
echo "      - ✅ Permissions: App Store Connect API enabled"
echo "      - ✅ Role: Developer or App Manager"
echo ""
echo "B. Check Team ID:"
echo "   1. Go to https://developer.apple.com/account/"
echo "   2. Membership → Team ID"
echo "   3. Verify it matches: YWQH3Z3Z85"
echo ""
echo "C. Check Bundle Identifier:"
echo "   1. Go to App Store Connect"
echo "   2. My Apps → Select your app"
echo "   3. Check bundle ID matches Xcode project"
echo ""

echo "7. QUICK FIXES TO TRY:"
echo "----------------------"
echo "Option 1: Add TEAM_ID as GitHub Secret"
echo "  - Name: TEAM_ID"
echo "  - Value: YWQH3Z3Z85"
echo ""
echo "Option 2: Update workflow to use secret instead of hardcoded:"
echo "  Change: TEAM_ID: YWQH3Z3Z85"
echo "  To: TEAM_ID: \${{ secrets.TEAM_ID }}"
echo ""
echo "Option 3: Trigger workflow with debug output:"
echo "  Go to GitHub → Actions → ios-release.yml → Run workflow"
echo "  Check 'Debug API Key Format' step output"
echo ""

echo "8. COMMON ERROR PATTERNS:"
echo "-------------------------"
echo "❌ 'No profiles for com.example.app were found'"
echo "   → Bundle ID mismatch or provisioning profile missing"
echo ""
echo "❌ 'Authentication credentials are missing or invalid'"
echo "   → API key permissions or format issue"
echo ""
echo "❌ 'Team ID YWQH3Z3Z85 is not valid'"
echo "   → Wrong team ID"
echo ""
echo "❌ 'Private key not in PEM format'"
echo "   → .p8 file content malformed in GitHub secret"
echo ""

echo "=== NEXT STEPS ==="
echo "1. Check latest workflow run logs in GitHub"
echo "2. Look for specific error message"
echo "3. Verify Apple Developer Portal settings"
echo "4. Update team ID if incorrect"
echo "5. Regenerate API key if permissions wrong"
echo ""

echo "Need the actual error from GitHub Actions to provide specific fix."